name: Validate Merge Strategy (Dynamic)

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      source_branch:
        required: true
        type: string
      target_branch:
        required: true
        type: string
      repo_full_name:
        required: true
        type: string

jobs:
  validate_merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Display PR details
        run: |
          echo "PR number: ${{ inputs.pr_number }}"
          echo "Source: ${{ inputs.source_branch }}"
          echo "Target: ${{ inputs.target_branch }}"
          echo "Repo: ${{ inputs.repo_full_name }}"

      - name: Fetch PR merge state
        id: get_method
        run: |
          echo "Fetching PR state..."
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ inputs.repo_full_name }}/pulls/${{ inputs.pr_number }} )

          MERGEABLE_STATE=$(echo "$RESPONSE" | jq -r '.mergeable_state')
          if [[ "$MERGEABLE_STATE" == "null" || -z "$MERGEABLE_STATE" ]]; then
            MERGEABLE_STATE="unknown"
          fi

          echo "merge_state=$MERGEABLE_STATE" >> $GITHUB_OUTPUT
          echo "Detected merge state: $MERGEABLE_STATE"

      - name: Validate merge rules
        id: validate
        run: |
          SRC="${{ inputs.source_branch }}"
          TGT="${{ inputs.target_branch }}"
          STATE="${{ steps.get_method.outputs.merge_state }}"

          echo "Validating PR..."
          echo "Source=$SRC Target=$TGT MergeableState=$STATE"

          # Allow 'merge' only from main -> develop
          if [[ "$SRC" == "main" && "$TGT" == "develop" ]]; then
            echo "✅ Merge allowed from main → develop."
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Require squash for feature → develop
          if [[ "$SRC" == feature/* && "$TGT" == "develop" ]]; then
            if [[ "$STATE" != "clean" ]]; then
              echo "❌ Invalid merge strategy/state: $STATE. Only squash allowed for feature → develop."
              echo "valid=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "✅ Valid merge (squash) from feature → develop."
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "ℹ️ No restrictions for this branch combination."
          echo "valid=true" >> $GITHUB_OUTPUT

      - name: Comment on PR if invalid
        if: steps.validate.outputs.valid == 'false'
        run: |
          MSG="❌ Invalid merge detected.
          Only **Squash and Merge** is allowed when merging from feature → develop."

          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\": \"$MSG\"}" \
            https://api.github.com/repos/${{ inputs.repo_full_name }}/issues/${{ inputs.pr_number }}/comments
          exit 1
